fix compile error for packagegroup-hostmobility-base and -can
Prevent build errors
    ERROR: packagegroup-hostmobility-base-1.0-r0 do_package_write_ipk: An allarch packagegroup shouldn't depend on packages which are dynamically renamed (libgpiod to libgpiod2)
    ERROR: packagegroup-hostmobility-base-1.0-r0 do_package_write_ipk: An allarch packagegroup shouldn't depend on packages which are dynamically renamed (libssl to libssl3)

    An allarch packagegroup shouldn't depend on packages which are dynamically renamed (libsocketcan to libsocketcan2)